<?php
/**
 * Frontend WebP delivery.
 *
 * @package Simple_Image_Optimizer
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Serves generated WebP files in safe WordPress frontend image output.
 */
class SIO_Frontend {
	/** @var SIO_Options */
	private $options;

	/** @var array<string,string> */
	private $url_cache = array();

	/**
	 * Constructor.
	 *
	 * @param SIO_Options $options Options.
	 */
	public function __construct( SIO_Options $options ) {
		$this->options = $options;
	}

	/** Register frontend hooks. */
	public function register_hooks() {
		add_filter( 'wp_get_attachment_image_src', array( $this, 'filter_attachment_image_src' ), 10, 4 );
		add_filter( 'wp_calculate_image_srcset', array( $this, 'filter_srcset_sources' ), 10, 5 );
		add_filter( 'wp_get_attachment_image_attributes', array( $this, 'filter_image_attributes' ), 10, 3 );
		add_filter( 'wp_content_img_tag', array( $this, 'filter_content_img_tag' ), 10, 3 );
	}

	/**
	 * Replace image source URL when a generated WebP sibling exists.
	 *
	 * @param array|false  $image Image data.
	 * @param int          $attachment_id Attachment ID.
	 * @param string|array $size Image size.
	 * @param bool         $icon Whether image should be an icon.
	 * @return array|false
	 */
	public function filter_attachment_image_src( $image, $attachment_id, $size, $icon ) {
		unset( $attachment_id, $size, $icon );

		if ( ! $this->should_serve_webp() || ! is_array( $image ) || empty( $image[0] ) || ! is_string( $image[0] ) ) {
			return $image;
		}

		$image[0] = $this->get_webp_url_for_url( $image[0] );
		return $image;
	}

	/**
	 * Replace srcset source URLs when generated WebP siblings exist.
	 *
	 * @param array  $sources Sources.
	 * @param array  $size_array Size array.
	 * @param string $image_src Image source.
	 * @param array  $image_meta Image metadata.
	 * @param int    $attachment_id Attachment ID.
	 * @return array
	 */
	public function filter_srcset_sources( $sources, $size_array, $image_src, $image_meta, $attachment_id ) {
		unset( $size_array, $image_src, $image_meta, $attachment_id );

		if ( ! $this->should_serve_webp() || ! is_array( $sources ) ) {
			return $sources;
		}

		foreach ( $sources as $width => $source ) {
			if ( isset( $source['url'] ) && is_string( $source['url'] ) ) {
				$sources[ $width ]['url'] = $this->get_webp_url_for_url( $source['url'] );
			}
		}

		return $sources;
	}

	/**
	 * Replace URLs in image attributes generated by WordPress.
	 *
	 * @param array        $attr Image attributes.
	 * @param WP_Post      $attachment Attachment object.
	 * @param string|array $size Image size.
	 * @return array
	 */
	public function filter_image_attributes( $attr, $attachment, $size ) {
		unset( $attachment, $size );

		if ( ! $this->should_serve_webp() || ! is_array( $attr ) ) {
			return $attr;
		}

		if ( ! empty( $attr['src'] ) && is_string( $attr['src'] ) ) {
			$attr['src'] = $this->get_webp_url_for_url( $attr['src'] );
		}

		if ( ! empty( $attr['srcset'] ) && is_string( $attr['srcset'] ) ) {
			$attr['srcset'] = $this->replace_srcset_urls( $attr['srcset'] );
		}

		return $attr;
	}

	/**
	 * Replace URLs in image tags processed through WordPress content filters.
	 *
	 * @param string $filtered_image Image HTML.
	 * @param string $context Context.
	 * @param int    $attachment_id Attachment ID.
	 * @return string
	 */
	public function filter_content_img_tag( $filtered_image, $context, $attachment_id ) {
		unset( $context, $attachment_id );

		if ( ! $this->should_serve_webp() || ! is_string( $filtered_image ) || '' === $filtered_image ) {
			return $filtered_image;
		}

		$with_src = preg_replace_callback(
			'/\s(src)=([\'"])(.*?)\2/i',
			function ( $matches ) {
				return ' ' . $matches[1] . '=' . $matches[2] . esc_url( $this->get_webp_url_for_url( html_entity_decode( $matches[3], ENT_QUOTES, get_bloginfo( 'charset' ) ) ) ) . $matches[2];
			},
			$filtered_image
		);
		$filtered_image = is_string( $with_src ) ? $with_src : $filtered_image;

		$with_srcset = preg_replace_callback(
			'/\s(srcset)=([\'"])(.*?)\2/i',
			function ( $matches ) {
				return ' ' . $matches[1] . '=' . $matches[2] . esc_attr( $this->replace_srcset_urls( html_entity_decode( $matches[3], ENT_QUOTES, get_bloginfo( 'charset' ) ) ) ) . $matches[2];
			},
			$filtered_image
		);
		$filtered_image = is_string( $with_srcset ) ? $with_srcset : $filtered_image;

		return $filtered_image;
	}

	/**
	 * Determine whether frontend WebP delivery should run.
	 *
	 * @return bool
	 */
	private function should_serve_webp() {
		if ( is_admin() || is_feed() || wp_doing_ajax() || ( defined( 'REST_REQUEST' ) && REST_REQUEST ) ) {
			return false;
		}

		$options = $this->options->get();
		return ! empty( $options['serve_webp_frontend'] );
	}

	/**
	 * Replace URLs in a srcset attribute value.
	 *
	 * @param string $srcset Source set.
	 * @return string
	 */
	private function replace_srcset_urls( $srcset ) {
		$candidates = preg_split( '/\s*,\s*/', trim( $srcset ) );
		if ( ! is_array( $candidates ) ) {
			return $srcset;
		}

		$replaced = array();
		foreach ( $candidates as $candidate ) {
			$parts = preg_split( '/\s+/', trim( $candidate ) );
			if ( ! is_array( $parts ) || empty( $parts[0] ) ) {
				continue;
			}

			$parts[0]   = $this->get_webp_url_for_url( $parts[0] );
			$replaced[] = implode( ' ', $parts );
		}

		return empty( $replaced ) ? $srcset : implode( ', ', $replaced );
	}

	/**
	 * Get a generated WebP URL for a local uploads URL when it exists.
	 *
	 * @param string $url Original image URL.
	 * @return string
	 */
	private function get_webp_url_for_url( $url ) {
		if ( isset( $this->url_cache[ $url ] ) ) {
			return $this->url_cache[ $url ];
		}

		$webp_url = $this->build_webp_url_for_upload_url( $url );
		if ( '' === $webp_url ) {
			$webp_url = $url;
		}

		$this->url_cache[ $url ] = $webp_url;
		return $webp_url;
	}

	/**
	 * Build WebP URL from an uploads URL after checking that the file exists.
	 *
	 * @param string $url Original image URL.
	 * @return string
	 */
	private function build_webp_url_for_upload_url( $url ) {
		if ( ! is_string( $url ) || '' === $url ) {
			return '';
		}

		$uploads = wp_get_upload_dir();
		if ( empty( $uploads['basedir'] ) || empty( $uploads['baseurl'] ) ) {
			return '';
		}

		$parsed_url  = wp_parse_url( $url );
		$parsed_base = wp_parse_url( $uploads['baseurl'] );
		if ( ! is_array( $parsed_url ) || ! is_array( $parsed_base ) || empty( $parsed_url['path'] ) || empty( $parsed_base['path'] ) ) {
			return '';
		}

		if ( ! empty( $parsed_url['host'] ) && ! empty( $parsed_base['host'] ) && strtolower( $parsed_url['host'] ) !== strtolower( $parsed_base['host'] ) ) {
			return '';
		}

		$path      = wp_normalize_path( rawurldecode( $parsed_url['path'] ) );
		$base_path = wp_normalize_path( untrailingslashit( $parsed_base['path'] ) );

		if ( 0 !== strpos( $path, $base_path . '/' ) ) {
			return '';
		}

		if ( ! preg_match( '/\.(jpe?g|png)$/i', $path ) ) {
			return '';
		}

		$relative      = ltrim( substr( $path, strlen( $base_path ) ), '/' );
		$webp_relative = preg_replace( '/\.[^.]+$/', '.webp', $relative );
		if ( ! is_string( $webp_relative ) || '' === $webp_relative || false !== strpos( $webp_relative, '../' ) ) {
			return '';
		}

		$base_dir  = wp_normalize_path( untrailingslashit( $uploads['basedir'] ) );
		$webp_path = wp_normalize_path( trailingslashit( $base_dir ) . $webp_relative );
		if ( 0 !== strpos( $webp_path, $base_dir . '/' ) || ! file_exists( $webp_path ) ) {
			return '';
		}

		$webp_url = trailingslashit( $uploads['baseurl'] ) . implode( '/', array_map( 'rawurlencode', explode( '/', wp_normalize_path( $webp_relative ) ) ) );
		if ( ! empty( $parsed_url['query'] ) ) {
			$webp_url .= '?' . $parsed_url['query'];
		}

		return $webp_url;
	}
}
